name: Cypress tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
          run_install: |
            - args: [----filter cypress-tests...]
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: pnpm --dir cypress/ cypress:ci